name: Release Binary

on:
  release:
    types: [created]  # Triggers when you create a release in the UI
  push:
    tags:
      - "v*"          # Triggers when you push a tag like v1.0.0

permissions:
  contents: write     # Required to upload files to the Release

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Windows Binary
        run: go build -v -o snipher.exe ./cmd/snipher

      - name: Build Linux Binary
        run: go build -v -o snipher-linux ./cmd/snipher

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            snipher.exe
            snipher-linux